[package]
name = "parser_helper"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/Clinery1/parser_helper"


[features]
logos = ["dep:logos"]


[dependencies]
logos = { version = "0.14.0", optional = true }
